AddCSLuaFile("xpdrp_inventory/sh_init.lua")
AddCSLuaFile("xpdrp_inventory/config/sh_config.lua")
AddCSLuaFile("xpdrp_inventory/config/sh_items.lua")
AddCSLuaFile("xpdrp_inventory/config/sh_recipes.lua")
AddCSLuaFile("xpdrp_inventory/config/sh_traders.lua")
AddCSLuaFile("xpdrp_inventory/config/sh_lootboxes.lua")
AddCSLuaFile("xpdrp_inventory/core/sh_utils.lua")
AddCSLuaFile("xpdrp_inventory/ui/cl_f4_menu.lua")
AddCSLuaFile("xpdrp_inventory/ui/cl_trader_menu.lua")

include("xpdrp_inventory/sh_init.lua")
include("xpdrp_inventory/config/sh_config.lua")
include("xpdrp_inventory/config/sh_items.lua")
include("xpdrp_inventory/config/sh_recipes.lua")
include("xpdrp_inventory/config/sh_traders.lua")
include("xpdrp_inventory/config/sh_lootboxes.lua")
include("xpdrp_inventory/core/sh_utils.lua")

include("xpdrp_inventory/core/sv_storage.lua")
include("xpdrp_inventory/core/sv_inventory.lua")
include("xpdrp_inventory/core/sv_net.lua")
include("xpdrp_inventory/core/sv_traders.lua")
include("xpdrp_inventory/core/sv_lootboxes.lua")